const express = require("express");
const router = express.Router();

const validate = require("../../validates/client/password.validate");
const controller = require("../../controllers/client/user.controller");
router.get("/register", controller.register);
router.post("/register", validate.valiPassword, controller.registerPost);
router.get("/login", controller.login);
router.post("/login", controller.loginPost);
router.get("/logout", controller.logout);
router.get("/password/forgot", controller.forgotPassword);
router.post("/password/forgot", controller.forgotPasswordPost);
router.get("/password/otp", controller.otpPassword);
router.post("/password/otp", controller.otpPasswordPost);
router.get("/password/reset", controller.resetPassword);
router.patch("/password/reset", validate.valiPassword, controller.resetPasswordPatch);
router.get("/profile", controller.profile);
router.get("/password-old", controller.oldPassword);
router.post("/password-old",validate.valiPassword,controller.oldPasswordPost);
module.exports = router;
